---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: downloading {{ clair_scanner_url }} to {{ clair_scanner_exe }}
  become: true
  become_user: root
  get_url:
    url: '{{ clair_scanner_url }}'
    dest: '{{ clair_scanner_exe }}'
    checksum: '{{ clair_scanner_checksum }}'
    mode: 0755
- name: linking {{ clair_scanner_link }} to {{ clair_scanner_exe }}
  become: true
  become_user: root
  file:
    src: '{{ clair_scanner_exe }}'
    dest: '{{ clair_scanner_link }}'
    state: link
